### PR TITLE
Added the main menu with options

### PR DESCRIPTION
**Pull request by devkristaps**
Added the initial look of the main menu with 4 options. We need to review the options before moving with merging I would say. Agree upon what we are going to do inside the menu.

@AppleBlu please, comment on this!

### CODE REVIEW

**Review by devkristaps — COMMENTED** [review]
Looks good

**Comment by AppleBlu** [comment]
Maybe it is possible to make a menu in a menu. Menu 1 = See and select banks, Menu 2 = calculate mortgage. Since you cant calculate mortgage before the bank has been selected including the other inputs like down payment.etc
my thought is 
menu 1
1.show banks interest rates
2.pick bank 
3.contact support
4.exit
menu 2
1.pick the price of house
2.pick the down payment
3.contact support
4.exit
user_choice = do you want to calculate mortgage?

**Comment by devkristaps** [comment]
Resolved the code conflict.

**Comment by devkristaps** [comment]
> Maybe it is possible to make a menu in a menu. Menu 1 = See and select banks, Menu 2 = calculate mortgage. Since you cant calculate mortgage before the bank has been selected including the other inputs like down payment.etc my thought is menu 1 1.show banks interest rates 2.pick bank 3.contact support 4.exit menu 2 1.pick the price of house 2.pick the down payment 3.contact support 4.exit user_choice = do you want to calculate mortgage? @devkristaps Let me know your thoughts

I was thinking about to add the bank when you are actually calculating mortgage. Before that you can check banks and rates as an example.

**Review by AppleBlu — CHANGES_REQUESTED** [review]
@devkristaps Change it to the example we discussed

**Comment by devkristaps** [comment]
> menu 1
> 1.show banks interest rates
> 2.pick bank
> 3.contact support
> 4.exit
> menu 2
> 1.pick the price of house
> 2.pick the down payment
> 3.contact support
> 4.exit
> user_choice = do you want to calculate mortgage?

Discussed and done

**Review by AppleBlu — APPROVED** [review]
Looks good!

**Pull request merged**
